### PR TITLE
Updated PR on adding XML support plus some amount of cleanup

### PR DESCRIPTION
**Pull request by ktbyers**
.

### CODE REVIEW

**Comment by ktbyers** [comment]
FYI, I am pretty sure that this code here in _build_payload is not working properly:

```
+        if len(commands) > 1:
+            command = 0
+            for item in commands:
+                if command == 0:
+                    command = item
+                else:
+                    command = '{}{}{}'.format(command, ' ;', item)
+        else:
+            command = commands[0]
```

**Comment by itdependsnetworks** [comment]
@jedelman8 Are you good with the License?

@ktbyers Just making sure there is no implications for the unicode change.

**Comment by ktbyers** [comment]
In general, I think it is better to have all strings unicode so that PY2/PY3 code compatibility is less of an issue (so yes, I don't think there should be an issue).

We should do a set of regression tests, however, prior to doing the next release to pypi. I also didn't look to much at your existing unit tests and whether they work or not (or are expected to work or not).

I saw they failed, but didn't think it was because of my changes (but we should look more into the status of the existing unit tests and get them into working state--if they are applicable).

**Comment by ktbyers** [comment]
@itdependsnetworks @jedelman8 Any update on this?

**Pull request merged**
