### PR TITLE
Ability to issue show commands via XML for NXAPI

### PR DESCRIPTION
**Pull request by mattschwen**
This PR comes from a need to implement XML based returns for NXAPI vs JSON.

Reference:
https://github.com/napalm-automation/napalm/pull/578

This specification comes from the cumbersome amount of bugs when Cisco converts XML to JSON. 

This PR is far from complete but wanted to show an example of how this is done. The `def _cli_command_xml(self, commands, method=u'cli_show'):` function will return straight `XML` with no parsing abilities.

### CODE REVIEW

**Comment by ktbyers** [comment]
@itdependsnetworks @mattschwen 

What should we do here? 

A couple of options: 1)Integrate in XML support into pynxos, 2)Integrate XML support for NX-API directly into NAPALM (and move some of the JSON-RPC functionality straight to NAPALM also).

Thoughts?

**Comment by ktbyers** [comment]
There probably will be a set of additional PRs coming. Also will need a new release to pypi (whenever we decide the XML support is ready).

**Comment by itdependsnetworks** [comment]
No issues pushing to pypi

**Comment by ktbyers** [comment]
@itdependsnetworks Can you make a `develop` branch that we can resubmit/merge this PR into (there is probably enough moving parts here that it is better that we merge into `develop`).

**Comment by itdependsnetworks** [comment]
Fixed merge conflict, print, created develop, and set PR to develop.

**Comment by ktbyers** [comment]
I will see if I can review this today or tomorrow. There was an issue that I saw that I want to fix.

**Comment by ktbyers** [comment]
@itdependsnetworks Should we rename `verify` to `ssl_verify` (to me it was unclear what that was doing until I looked at it a bit more).

Also I think that change will probably break NAPALM (as it defaults to verify=True so anything that is self-signed will fail). Do we want to default that ssl_verify to False?

**Comment by ktbyers** [comment]
Also what about switching to 'https' as the default transport?

**Pull request merged**
